services:
  nginx:
    image: nginx:1.26.2-alpine3.20
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - laravel
    platform: linux/arm64

  php:
    image: php8.4-pdomysql
    container_name: php
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./public:/var/www/html/public
    networks:
      - laravel
    platform: linux/arm64

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file: ".env"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
      MYSQL_SSL_CA: /var/lib/mysql/ca.pem
      MYSQL_SSL_CERT: /var/lib/mysql/server-cert.pem
      MYSQL_SSL_KEY: /var/lib/mysql/server-key.pem
    networks:
      - laravel
    volumes:
      - ./mysql_data:/var/lib/mysql

networks:
  laravel:
